### ISSUE TITLE
Can't generate PDF output of RFC document

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-templates-ietf#31]
From this PR: https://github.com/metanorma/mn-templates-ietf/pull/30

I use this command:
```
bundle exec metanorma -t ietf -x pdf rfc/document.adoc
```

and get:
```
    Cannot generate PDF due to missing external libraries.
    ------------------------------------------------------

    In order to generate PDFs, xml2rfc uses the WeasyPrint library, which
    depends on external libraries that must be installed as native packages.

    1. First, install the Pango, and other required libraries on your
    system.  See installation instructions on the WeasyPrint Docs:

        https://doc.courtbouillon.org/weasyprint/stable/first_steps.html

    2. Next, install weasyprint python modules using pip.

        pip install 'weasyprint>=53.0'


    3. Finally, install the full Noto Font and Roboto Mono packages:

       * Download the full font file from:
         https://noto-website-2.storage.googleapis.com/pkgs/Noto-unhinted.zip
         or follow the 'DOWNLOAD ALL FONTS' link on this page:
         https://www.google.com/get/noto/

       * Follow the installation instructions at
         https://www.google.com/get/noto/help/install/

       * Go to https://fonts.google.com/specimen/Roboto+Mono, and download the
         font. Follow the installation instructions above, as applied to this
         download.

       * Go to https://fonts.google.com/noto/specimen/Noto+Sans+Math, and
         download the font. Follow the installation instructions above, as
         applied to this download.

    With these libraries, modules, and fonts installed and available to
    xml2rfc, the --pdf switch will be enabled.

Could not import weasyprint
Could not find the pango lib
```

Are you able to build a PDF from this document: https://github.com/metanorma/mn-templates-ietf/pull/30, @Intelligent2013?

**Comment by Intelligent2013** [comment]
@manuelfuenmayor I didn't develop XSLT for IETF, so you can't generate PDF by `mn2pdf` tool.

I've tried to install:
- GTK from https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases
- WeasyPrint by the instruction https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows

Note: May you need to use `python` instead of `python3`.

and after that I'm not able to build PDF too:
```
bundle exec metanorma -t ietf -x pdf rfc/document.adoc
[relaton] (IETF.TLP) not found.
Bibliography: (XML Line 000291): Reference RNP is missing a document identifier (docid)
Metanorma XML Style Warning: (XML Line 000065): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000072): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000138): Table should have title
Metanorma XML Syntax: (XML Line 000007:46): element "contributor" not allowed yet; missing required element "docidentifier"
Metanorma XML Syntax: (XML Line 000175:80): attribute "inline-header" not allowed here; expected attribute "language", "numbered", "obligation", "removeInRFC", "script" or "toc"

-----

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting

-----


-----

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting

-----

Traceback (most recent call last):
  File "C:\Python310\Scripts\xml2rfc-script.py", line 33, in <module>
    sys.exit(load_entry_point('xml2rfc==3.14.2', 'console_scripts', 'xml2rfc')())
  File "C:\Python310\Scripts\xml2rfc-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Python310\lib\site-packages\xml2rfc\__init__.py", line 38, in <module>
    from weasyprint.text.ffi import pango
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1405, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1255, in __iter__
  File "<frozen importlib._bootstrap_external>", line 1242, in _recalculate
  File "<frozen importlib._bootstrap_external>", line 1238, in _get_parent_path
KeyError: 'weasyprint'
```

I don't have an ideas how to solve it.

**Comment by Intelligent2013** [comment]
Update: to build PDF with using of WeasyPrint, just move path to the GTK3 at first place in the environment variable `PATH`:
![image](https://github.com/metanorma/mn-templates-ietf/assets/5559926/22ba1d51-a045-48e6-a89d-db746c82c50d)

Found here: https://stackoverflow.com/questions/63449770/oserror-cannot-load-library-gobject-2-0-error-0x7e

Resulted PDF: [document.pdf](https://github.com/metanorma/mn-templates-ietf/files/12709155/document.pdf)

**Comment by Intelligent2013** [comment]
To check `weasyprint` installation:
```
python -m weasyprint --info
```
The resulte should be like this:
```
System: Windows
Machine: AMD64
Version: 10.0.19045
Release: 10
WeasyPrint version: 59.0
Python version: 3.10.6
Pydyf version: 0.7.0
qPango version: 15003
```

**Comment by manuelfuenmayor** [comment]
Wow, that was awesome, @Intelligent2013. Thank you!
(I wonder why there are so many steps to build a PDF in IETF, while in other flavors there aren't.)

Thanks @Intelligent2013, closing.

**Comment by ronaldtse** [comment]
@manuelfuenmayor because IETF PDF is built through the IETF xml2rfc tool, it is the only authorized way to build it.
